codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: 5
    patch: false
- name: Profile Readme
  uses: actions-js/profile-readme@v1
